# APPLICATION
platform.api:
    baseUrl: /api
    version: /v1
platform.proxy: false

# SERVER
server.port: 8082
server.servlet.context-path: /mcp/demo
server.tomcat:
      access_log_enabled: true
      basedir: target/tomcat

# LOG
logging:
  level:
    com.minsait.onesait: DEBUG
    org.springframework.security.level: ERROR
  file: /var/logs/mcp_demo.log
  pattern.console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'     

# LANGUAGE 
message.locale: ES

# SPRING  
spring:
  application.name: MCP_DEMO
  mvc.pathmatch.matching-strategy: ant-path-matcher
  main.allow-bean-definition-overriding: true
  main.allow-circular-references: true

  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialize: true
  
  h2:
    console.enabled: true
    console.path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties.hibernate.format_sql: true    

#  sql.init.data-locations: data-h2.sql    

# SWAGGER
swagger.basepackages: com.mcp.demo
swagger.serviceName: DemoServices
